server:
  port: 8002

spring:
  application:
    name: basis2
  zipkin:
    base-url: http://localhost:9411
    sleuth:
      sampler:
        #      抽样率。默认0.1,数值越大，对系统性能的影响越大
        probability: 1.0
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        #        cluster-name:
        #        namespace:
        #元数据配置
#        metadata:
#          key1: value1
#          key2: value2