server:
  port: 8002

spring:
  application:
    name: basis2
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        #        cluster-name:
        #        namespace:
        #元数据配置
#        metadata:
#          key1: value1
#          key2: value2