server:
  port: 8001

spring:
  application:
    name: basis
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
#        cluster-name:
#        namespace:

#配置服务的负载均衡规则
basis2:
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule
#    NFLoadBalancerClassName: ILoadBalancer实现类
#    NFLoadBalancerPingClassName: IPing实现类
#    NIWSServerListClassName: ServerList实现类
#    NIWSServerListFilterClassName: ServerListFilter实现类