server:
  port: 1111
spring:
  application:
    name: gateway
  cloud:
    nacos:
      server-addr: localhost:8848
    gateway:
      discovery:
        locator:
#          让gateway通过服务发现组件找到其他微服务
          enabled: true
      routes:
        - id: basis_route
#          uri: localhost:8001
          uri: lb://basis
          predicates:
#            - After=2017-01-20T17:42:47.789-07:00[America/Denver]
#            - After=2021-07-23T00:00:00+08:00[Asia/Shanghai]
#            - After=2021-07-21T18:59:40.888481300+08:00[Asia/Shanghai]
#            - Query=a, 1.
            - Path=/*/basisTest/**
#          filters:
#            - AddRequestHeader=X-Request-red, blue
        - id: basis2_route
          uri: lb://basis2
          predicates:
#            - After=2021-07-21T18:59:40.888481300+08:00[Asia/Shanghai]
            - Path=/*/basis2Test/**
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always